Repository Nayanika1402/RuRal-ReTreats, pull requests merged in 2025-04, with the labels that each got.

#124 enhance footer
  Adventure.html
  CSS/Adventure.css
Labels: apertre2.0, Easy

#130 Update style.css
  CSS/style.css
Labels: enhancement, apertre2.0, Medium

#132 Changes made
  Budget.html
  CSS/Budget.css
Labels: apertre2.0, Hard

#133 Update style.css
  CSS/style.css
Labels: apertre2.0, Hard

#134 feat:Updated Budget Webpage fully
  Adventure.html
  Budget.html
  CSS/Adventure.css
  CSS/Budget.css
  JS/Budget.js
Labels: apertre2.0, Hard

#139 Changes the traveller section
  CSS/homestays.css
  CSS/style.css
  index.html
Labels: apertre2.0, Medium

#140 Changes the footer section information
  CSS/homestays.css
  CSS/style.css
  index.html
Labels: apertre2.0, Easy

#141 Made the modification
  .vscode/settings.json
  CSS/about.css
  CSS/blog.css
  CSS/contact.css
  CSS/faq.css
  CSS/homestays.css
  CSS/pp.css
  CSS/servicesstyle.css
  CSS/style.css
  CSS/t&c.css
  CSS/travelSustain.css
  blog.html
  contact.html
  faq.html
  homestays.html
  index.html
  pp.html
  services.html
  t&c.html
Labels: apertre2.0, Hard

#181 Update the contact section
  CSS/contact.css
  CSS/homestays.css
Labels: apertre2.0, Easy

#182 Update the explore more
  CSS/homestays.css
Labels: apertre2.0, Easy

#184 Changes the learn more button
  CSS/style.css
Labels: apertre2.0, Easy

#194 Enhance the faq section
  CSS/contact.css
  CSS/faq.css
  CSS/homestays.css
  CSS/servicesstyle.css
  CSS/style.css
  homestays.html
Labels: apertre2.0, Medium

#190 Add effects to subscribe
  CSS/blog.css
  CSS/servicesstyle.css
  CSS/style.css
Labels: apertre2.0, Easy

#187 Changes the send messages button
  CSS/style.css
Labels: apertre2.0, Easy

#210 Fix the traveler section
  CSS/style.css
Labels: apertre2.0, Easy

#211 Update the homestay section
  CSS/homestays.css
Labels: apertre2.0, Hard

#212 Update the booking
  CSS/homestays.css
Labels: apertre2.0, Medium

#213 Update the button
  CSS/homestays.css
Labels: apertre2.0, Medium

#214 Updated the chatbot
  CSS/contact.css
  CSS/homestays.css
Labels: apertre2.0, Hard

#215 Update the enhance know more
  CSS/about.css
  CSS/homestays.css
Labels: apertre2.0, Hard

#219 feat:All Webpages CSS updated and fixed
  Adventure.html
Labels: apertre2.0, Hard

#225 feat:Added Splash Screen
  CSS/splash.css
  JS/splash.js
  index.html
Labels: apertre2.0, Hard

#228 feat:Corrected & Updated the PULL REQUEST TEMPLATE
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: apertre2.0, Hard

#229 Footer Fix
  CSS/about.css
  CSS/contact.css
  CSS/faq.css
  CSS/homestays.css
  CSS/pp.css
  CSS/servicesstyle.css
  CSS/style.css
  CSS/t&c.css
  about.html
Labels: apertre2.0, Medium

#232 Update
  CSS/blog.css
  CSS/style.css
  JS/blog.js
Labels: apertre2.0, Medium

#235 Fixed the time delay in the loading
  JS/script.js
  JS/splash.js
Labels: apertre2.0, Easy

#237 Home Page collapsible navbar fixed and all Links updated based on pro…
  Adventure.html
  Budget.html
  CSS/homestays.css
  CSS/pp.css
  CSS/style.css
  JS/Adventure.js
  JS/Budget.js
  JS/about.js
  JS/blog.js
  JS/contact.js
  JS/faq.js
  JS/homestays.js
  JS/navbar.js
  JS/pp.js
  JS/script.js
  JS/servicesscript.js
  JS/t&c.js
  JS/ts.js
  about.html
  blog.html
  contact.html
  faq.html
  homestays.html
  index.html
  login.html
  pp.html
  services.html
  t&c.html
  ts.html
Labels: apertre2.0, Hard

#242 Enhance the homestays page
  CSS/homestays.css
  homestays.html
Labels: apertre2.0, Hard

#245 Update the blog section
  CSS/blog.css
  CSS/style.css
Labels: apertre2.0, Medium

#248 Update the blog
  CSS/style.css
Labels: apertre2.0, Medium

#244 Navbar behaviour fixed
  Adventure.html
  Budget.html
  CSS/about.css
  CSS/navbar.css
  CSS/style.css
  about.html
  blog.html
  contact.html
  faq.html
  homestays.html
  index.html
  login.html
  pp.html
  services.html
  t&c.html
  ts.html
Labels: apertre2.0, Easy

#263 Fixed Testimonial Section
  CSS/style.css
Labels: apertre2.0, Easy
