Repository Nayanika1402/RuRal-ReTreats, pull requests merged in 2025-03, with the labels that each got.

#72 Added issue and pr template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: apertre2.0, Doc

#86 ReadMe doc Tweak
  README.md
Labels: enhancement, apertre2.0, Doc

#87 improved hover effect in footer icons
  .vscode/settings.json
  CSS/about.css
  CSS/contact.css
  CSS/faq.css
  CSS/homestays.css
  CSS/pp.css
  CSS/servicesstyle.css
  CSS/style.css
  CSS/t&c.css
  README.md
Labels: enhancement, apertre2.0, Easy

#90 Dev
  CSS/servicesstyle.css
  services.html
Labels: apertre2.0, Medium

#95 feat: Updated ServicePage
  CSS/servicesstyle.css
  JS/servicesscript.js
  services.html
Labels: apertre2.0, Hard

#98 feat: Added Favicon
  Adventure.html
  Budget.html
  about.html
  blog.html
  contact.html
  faq.html
  favicon/about.txt
  favicon/favicon-114x114.png
  favicon/favicon-120x120.png
  favicon/favicon-144x144.png
  favicon/favicon-152x152.png
  favicon/favicon-16x16.png
  favicon/favicon-180x180.png
  favicon/favicon-192x192.png
  favicon/favicon-32x32.png
  favicon/favicon-512x512.png
  favicon/favicon-57x57.png
  favicon/favicon-60x60.png
  favicon/favicon-72x72.png
  favicon/favicon-96x96.png
  favicon/favicon.ico
  favicon/manifest.json
  homestays.html
  index.html
  login.html
  pp.html
  services.html
  t&c.html
  travelSustain.html
Labels: apertre2.0, Easy

#107 Restrict Letters in Number Field
  CSS/contact.css
  JS/contact.js
  contact.html
  homestays.html
Labels: apertre2.0, Easy

#109 Added essential meta tags for SEO optimization
  about.html
  contact.html
  faq.html
  homestays.html
  index.html
  services.html
Labels: apertre2.0, Easy

#112 feat: Updated Blog Section
  CSS/about.css
  CSS/faq.css
  CSS/homestays.css
  CSS/pp.css
  CSS/servicesstyle.css
  CSS/style.css
  CSS/t&c.css
  JS/script.js
  index.html
Labels: apertre2.0, Medium

#114 feat: Updated Adventure Page
  Adventure.html
  CSS/Adventure.css
  JS/Adventure.js
Labels: apertre2.0, Hard

#117 feat: Improved filter section
  CSS/homestays.css
  homestays.html
Labels: apertre2.0, Easy
